# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Token Ranges Service

# Triggers
on:
  push:
    branches: [ "main" ]
    paths:
      - TokenRanges/**
  pull_request:
    branches: [ "main" ]
    paths:
      - TokenRanges/**

# A job has several Steps (Like building the code or deploying the code)
jobs:
  # Job Build
  build:
    # OS where will the code will run
    runs-on: ubuntu-latest

    # Steps are the "recipe"
    steps:
      # Checkout the code from the repo
      - uses: actions/checkout@v4
  
      # Then, get the .net for my runner
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
  
      # Restore the nuget packages
      - name: Restore dependencies
        run: dotnet restore
  
      # Then, build the project but not restore the nugets (It already ran)
      - name: Build
        run: dotnet build --no-restore
  
      # Test the code, in case the project has Unit Tests
      - name: Test
        run: dotnet test --no-build --verbosity normal
  
      - name: dotnet publish
        run: dotnet publish TokenRanges/src/UrlShortener.TokenRangeService -c Release -o ${{env.DOTNET_ROOT}}/myapp
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Upload SQL artifact for DB deployment job
        uses: actions/upload-artifact@v4
        with:
          name: pg-script
          path: TokenRanges/src/UrlShortener.TokenRangeService/TokenRangesTable.sql
  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: Development
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Download DB artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: pg-script

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
    
      # Those secrets can be grabbed from Azure > Postgre DB and saved Github per each environment
      - name: Deploy Database Schema
        env:
          PGHOST: ${{ secrets.PG_SQL_HOST }}
          PGDATABASE: ranges # This is the name defined in the Bicep File to create the Postgre SQL Database
          PGUSER: ${{ secrets.PG_SQL_ADMINUSER }}
          PGPASSWORD: ${{ secrets.PG_SQL_PASSWORD }}
        run: psql -f src/UrlShortener.TokenRangeService/TokenRangesTable.sql
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{vars.TOKENRANGES_RESOURCE_NAME}}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_TOKENRANGES_PUBLISH_PROFILE }}
          package: .